function [atslDef,varargout]=define_atsl
% ** function atsl=define_atsl
% defines an 'advanced time stamp list' 
% -> see define_atsl.rtf for an explanation of the parameters
% varargout: struct array with parameters as fields and default values

% first column: name of parameter
% second column: default value
% third column: format string (e.g. for use with fprintf)
% fourth column: unit (empty string if not applicable)

atslDef={...
'atsl_version',     1.0,      '%20.1f', '';...
'rectime',          nan,      '%20.3f', 's';...
'ephys_filename',   'unknown','%20s',   '';...
'ephys_chan',       'unknown','%20s',   '';...
'ev_threshold',     nan,      '%20.5f', 'mV';...
'burst_interval1',  nan,      '%20.2f', 'ms';...
'burst_interval2',  nan,      '%20.2f', 'ms';...
'burst_minev',      nan,      '%20.0f', '';...
'silentper_dur',    nan,      '%20.2f', 'ms';...
'silentper_maxev',  nan,      '%20.0f', '';...
'data_quality',     nan,      '%20.0f', '';...
'comment',          'none',   '%20s',   '';...
};

if nargout>1
  nField=size(atslDef,1);
  for j=1:nField
    s.(atslDef{j,1})=atslDef{j,2};
  end
  varargout{1}=s;
end